#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include "upholsterer2k/opcode_specification.h"

typedef struct {
    UP2K_OpcodeSpecification* specifications;
    size_t num_specifications;
} UP2K_OpcodeList;

// the opcodes.c file must be auto-generated by ./tools/opcodes2c.py
UP2K_OpcodeList UP2K_opcode_specifications();

#ifdef __cplusplus
}
#endif
